version: "3"
services:
        app:
                image: jgwill/node
                container_name: my_app2
                command: sh -c "/app/service.sh"
                ports:
                        - 3001:3001
                working_dir: /app
                volumes:
                        - ./:/app
                environment:
                        logfile: /app/log-secondservice.log
                        MYVAL: allo
                        MYVAL2: haha
        

                        