FROM runwayml/model-runner:gpu-python2.7-cuda9.0-runtime
#FROM runwayml/model-runner:gpu-python2.7-cuda9.2-runtime


RUN apt update
RUN apt upgrade -y

RUN apt install git vim -y

RUN apt-get install libsm6 libxrender1 libfontconfig1 -y

